function create_asym_pdiffs_figure(zdata1)
%CREATEFIGURE(ZDATA1)
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 11-Dec-2018 15:46:44

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surf
surf(zdata1,'Parent',axes1,'EdgeColor','none');

% Create xlabel
xlabel('\phi_0','FontSize',33);

% Create title
title('Asymptotic Phase Differences, 2-point case','FontSize',33);

% Create ylabel
ylabel('c_{MA}','FontSize',33);

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 11]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',30,'XTickLabel',{'0','0.25','0.5','0.75','1',''},...
    'YTickLabel',{'1.1','1.9','2.7','3.4','4.2','5'});
% Create colorbar
colorbar('peer',axes1,'FontSize',27);

